### ISSUE TITLE
Start and Room > Your wishes Error  Bad Request: can't parse entities: Unsupported start tag

### ISSUE THREAD

**Issue by anmv** [pavel-glukhov/async_secret_santa_bot#15]
I create room
And move Room -> Your wishes

I get error:

```python
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Documents/Development/HomeProjects/Secret-Santa-Telegram-Bot/app/web/routers/webhooks.py", line 14, in webhook_endpoint
    return await handle_webhook(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Documents/Development/HomeProjects/Secret-Santa-Telegram-Bot/app/web/routers/webhooks.py", line 25, in handle_webhook
    await dp.feed_webhook_update(bot, update)
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 425, in feed_webhook_update
    response: Any = process_updates.result()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 368, in _feed_webhook_update
    return await self.feed_update(bot, update, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Documents/Development/HomeProjects/Secret-Santa-Telegram-Bot/app/bot/middlewares/database_middleware.py", line 22, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Documents/Development/HomeProjects/Secret-Santa-Telegram-Bot/app/bot/middlewares/languages_middleware.py", line 52, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/exorciste/Documents/Development/HomeProjects/Secret-Santa-Telegram-Bot/app/bot/handlers/wishes/wishes_general_menu.py", line 43, in show_wishes
    await message.edit_text(text=message_text,
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/client/bot.py", line 494, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/exorciste/Library/Caches/pypoetry/virtualenvs/secret-santa-telegram-bot-IEdPf5Ri-py3.12/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "app.store.database.models.wishroom" at byte offset 28
```

I printed var "wishes"
and get = "<app.store.database.models.WishRoom object at 0x108cdfa10>"

Please help me fix it

I try ENG and RU language

Your bot is nice ^_^

**Comment by anmv** [comment]
error file: wishes_general_menu.py

```python
@router.callback_query(F.data.startswith('room_show-wish'))
async def show_wishes(callback: types.CallbackQuery,
                      session: Session,
                      app_text_msg: TranslationMainSchema):
    room_number = get_room_number(callback)
    message = callback.message
    keyboard_inline = generate_inline_keyboard(
        {
            app_text_msg.buttons.wishes_menu.change_wish: f"room_change-wish_{room_number}",
            app_text_msg.buttons.return_back_button: f"room_menu_{room_number}",

        }
    )
    user_id = message.chat.id
    wishes = await WishRepo(session).get(user_id, room_number)

    message_text = app_text_msg.messages.wishes_menu.your_wishes.format(
        wishes=wishes
    )
    await message.edit_text(text=message_text,
                            reply_markup=keyboard_inline)
                            
```

**Comment by pavel-glukhov** [comment]
@amv thank you for reporting the issue . I'll check the one in next 2-3 days and push new commit.

**Comment by pavel-glukhov** [comment]
Fixed

![изображение](https://github.com/user-attachments/assets/74c01be4-df0c-43dc-abc0-ac6e55a185ed)
